### ISSUE TITLE
Parameters in a Json request should be optional

### ISSUE THREAD

**Issue by dragos** [dhpcs/play-json-rpc#1]
According to the [spec](http://www.jsonrpc.org/specification#request_object):

>params
>A Structured value that holds the parameter values to be used during the invocation of the method. This member MAY be omitted.

However, `JsonRpcRequestMessage` requires a `params` section.

**Comment by dhpiggott** [comment]
Ah, yes, so it should be. I'm not sure how I overlooked that before, so thanks for bringing it to my attention.

I'll see if I can bring the project up to date, fix this issue, and then do a release in the next few days.

**Comment by dragos** [comment]
I'm not sure what needs to be brought up to date, but I'm happy to open a PR for this issue.

**Comment by dhpiggott** [comment]
Thanks for the offer. I wish I could accept it, but I've already made the fix. (It's just not pushed yet due to needing to update the README).

I had made a few changes and releases since v1.0.0 that I'd not pushed to GitHub or released publicly. Most of them were just issues of style/simplicity/minimalism/dependency updates, but there was at least one that in a sense changed the API (due to changing the namespace of a type).

I brought everything except the README up-to-date yesterday, then fixed this issue* and prepared the release. So the one remaining task I have is to update the README, which I hope to do this evening. Once I've done that I'll push the changes and the release.

*I changed params from `Either[_]` to `Option[Either[_]]`. Let me know if that isn't the way you think it should be done, I'm open to other ideas!

**Comment by dragos** [comment]
That's what I had in mind. In fact I was about to push my changes, but I'll wait for your fix then. Thanks a lot!

I noticed another thing: `id` is `Option[Either]]`, but according to the spec it should always be provided for requests. If it's absent, it's a notification. Should I open another ticket for simplifying the signature of `id` in requests?

**Comment by dhpiggott** [comment]
It's reassuring you had the same solution in mind!

Re. `id` being `Option[_]`, my interpretation of the spec makes it the only safe type for `id`. Looking at http://www.jsonrpc.org/specification#request_object I read under **id** that:

> An identifier established by the Client that MUST contain a String, Number, or NULL value if included. If it is not included it is assumed to be a notification. The value SHOULD normally not be Null [1] and Numbers SHOULD NOT contain fractional parts [2].

But note [1] is this:

> [1] The use of Null as a value for the id member in a Request object is discouraged, because this specification uses a value of Null for Responses with an unknown id.

So my understanding is that null is only discouraged, not forbidden. Using `Option[_]` is intended to ensure compatibility with peers that set the value to null.

**Comment by dragos** [comment]
That's true, I was using a higher level [protocol](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md) that specifies `id` to be non-null. I guess we're stuck with an optional there.
