### ISSUE TITLE
Support overlapping parameter types

### ISSUE THREAD

**Issue by dragos** [dhpcs/play-json-rpc#2]
Some protocols use the same parameters for several requests, for example the [language server protocol](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md).

Currently this isn't supported, and [MethodFormats](https://github.com/dhpcs/play-json-rpc/blob/master/play-json-rpc/src/main/scala/com/dhpcs/jsonrpc/MessageCompanions.scala#L126) adds a runtime check.

This looks like an unnecessary restriction. Clients should be able to specify the method name they want to invoke together with its parameters instead of relying on disjunct parameter types.

**Comment by dhpiggott** [comment]
Thanks for reporting this. Just to check I've understood the issue you're describing, can you confirm that simply removing lines 122-130 would be the fix for it?

**Comment by dragos** [comment]
I'm not sure. You probably want to check non-overlapping types when "writing", but not when "reading". I guess the natural split is between the `CommandCompanion` and `ResponseCompanion` classes. Currently the choice of the `Format` instance is based on the class tag of the argument to `write`.

Or, alternatively, add the `method` as a discriminator for writing.

**Comment by dhpiggott** [comment]
Oops, yes, the restriction is currently needed to ensure the write-side works as expected given the way `CommandCompanion` works.

It's not clear what the best modification to the write-side would be to accommodate this. I'd prefer not to require that every call to `Command.write` specifies the method as an additional param.

In the cases where you have multiple commands of the same format, what would the ideal call to `write` look like for you?

**Comment by dragos** [comment]
In my case I'm only implementing the server-side so I don't think I need the write-side. However, I think the easiest would be to add a method parameter to disambiguate, if that can be done without disturbing the other use-cases. I don't see a way around this, since the rpc envelope needs the method name

**Comment by dhpiggott** [comment]
What I meant was that I'd prefer an approach that would only require explicitly specifying the method name when overlapping `Command` types are registered, and which continues to allow `Command.write` to be called without the method name when there are no overlapping types.

There is an alternative solution that doesn't require removing the requirement that types do not overlap (and thus avoids requiring that the method be specified for some/all command writes): how about simply duplicating message case classes for these cases? Depending on the exact nature of use (I guess primarily how common it is for different methods to have the same params) it might overall be more readable/maintainable, despite not being as DRY as it could be, because I think a 1:1 mapping between method names and types for marshalling is the simplest to think about. This would work for all use cases, it's just a question of how elegant (or not) it would end up being. Would this way not work well for you?

**Comment by dragos** [comment]
In this particular protocol there are 5 different requests that take the same arguments (essentially a source code position): hover, hyperlinking, documentation request, completions and document highlight.

I thought about duplicating these case classes, but it's not something I'm keen on doing. I'd need to define the formatter as well, and generally it sounds a bit restrictive.

What about an overloaded `write` definition, one that takes the method name as well? The original one can delegate to this one. It's up to the caller to go through the explicit method name if parameters are overlapping.

**Comment by dhpiggott** [comment]
Conceptually there are a couple of other reasons I'm reluctant to allow passing the method name in to `write` that I failed to identify before:

1. I don't think of the `Command`/`Response`/`Notification` case classes as being just an encoding of method params. I think of them as encoding both the _method_ and the params, and it's this that enables pattern matching to be used to build response handlers. Treating them as just encodings of the params doesn't provide the information needed to do this (unless you were to match directly on the method string [obtaining the constant from where?], but this wouldn't feel great to me because it would leak detail of how the protocol ADT is encoded into the application logic).

2. The pattern of defining the `*Formats` "registries" for each type of message provides a canonical source of truth for what will be sent and received over the wire and via which method names. Allowing method names to be overridden in calls to `write` would result in some of this information being distributed to call-sites, so they'd no longer be single sources of truth. Moreover there's no reason override the method name if the types that are registered in the `*Formats` "registries" each correspond to single  `Command`/`Response`/`Notification` as intended.

I do recognise that duplicating the same case class five times with a different name maybe isn't ideal either. But I think there is a another solution: composition. Could something like the following work for you?

```
...

case class TextDocumentPositionParams(textDocument: TextDocumentIdentifier, position: Position)

...

case class TextDocumentCompletionCommand(positionParams: TextDocumentPositionParams) extends ServerCommand

case class TextDocumentDefinitionCommand(positionParams: TextDocumentPositionParams) extends ServerCommand

case class TextDocumentDocumentSymbolCommand(textDocument: TextDocumentIdentifier) extends ServerCommand

object ServerCommand extends CommandCompanion[ServerCommand] {
  override val CommandFormats = {
    implicit val positionParamsFormat = Json.format[TextDocumentPositionParams]
    Message.MessageFormats(
      "initialize" -> Json.format[InitializeCommand],
      "shutdown" -> ShutdownCommand.format,
      "textDocument/completion" -> valueFormat(TextDocumentCompletionCommand)(_.positionParams),
      "textDocument/definition" -> valueFormat(TextDocumentDefinitionCommand)(_.positionParams),
      "textDocument/documentSymbol" -> Json.format[TextDocumentDocumentSymbolCommand])
  }
}

...
```

where `valueFormat` would be something like the following, and could be included as a helper in `play-json-rpc` itself if desired:

```
  def valueFormat[A, B: Format](apply: B => A)(unapply: A => B): Format[A] = new Format[A] {
    override def reads(json: JsValue) = Reads.of[B].reads(json).map(apply(_))
    override def writes(o: A) = Writes.of[B].writes(unapply(o))
  }
```

Note that I've replaced all the `Params` suffixes with `Command` because they suggest the case classes represent only the params, whereas as noted above my intent is that the concrete types of a `*Command` trait represent the method _and_ the params.

**Comment by dragos** [comment]
I understand your concerns, but as I mentioned, I'm not really keen on defining this boilerplate.

As this is a weekend project, for the moment I forked your repo and removed the overlapping check. I may revert to your solution in the end. I'll close this ticket.
